
AC_DEFUN([AX_BRIDGE],
[

	BRIDGE_BINDING=none
	AC_SUBST(BRIDGE_BINDING)

	BRIDGE_BATCH_SYSTEM=none
	AC_SUBST([BRIDGE_BATCH_SYSTEM])
	BRIDGE_BATCH_PLUGIN=none
	AC_SUBST([BRIDGE_BATCH_PLUGIN])

	BRIDGE_RM_SYSTEM=none
	AC_SUBST([BRIDGE_RM_SYSTEM])
	BRIDGE_RM_PLUGIN=none
	AC_SUBST([BRIDGE_RM_PLUGIN])

])
