stages:
  - build

build-rpm:
  stage: build
  script:
    - ./configure --with-slurm --with-slurm-lib
    - make
    - make dist
    - test -d $CCCSCRATCHDIR/bridge/rpmbuild && rm -fr $CCCSCRATCHDIR/bridge/rpmbuild/
    - mkdir -p $CCCSCRATCHDIR/bridge/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - cp bridge-*.tar.gz $CCCSCRATCHDIR/bridge/rpmbuild/SOURCES/
    - cp bridge.spec $CCCSCRATCHDIR/bridge/rpmbuild/SPECS/
    - cd $CCCSCRATCHDIR/bridge/rpmbuild/
    - rpmbuild --define "_topdir `pwd`" -v -ba SPECS/bridge.spec
    - cd -
    - mkdir dist
    - cp $CCCSCRATCHDIR/bridge/rpmbuild/RPMS/x86_64/bridge-*.rpm $CCCSCRATCHDIR/bridge/rpmbuild/SRPMS/bridge-*.rpm dist/
  artifacts:
    paths:
      - dist/bridge-*.rpm
    expire_in: 1 week
