variables:
  CI_CCC_WITH_DOCKER: "true"
  CI_CCC_TIMELIMIT: "60"

default:
  interruptible: true
  tags:
    - gitlab-runner-pcocc

stages:
  - check
  - basebuild
  - build

rpm-check:
  stage: check
  script:
    - docker run --rm -v "$PWD":/perfecto -w /perfecto essentialkaos/perfecto -I PF2,PF12,LNT0 bridge.spec

build-dist:
  stage: basebuild
  script:
    - ./autogen.sh
    - ./configure --with-slurm --with-slurm-lib
    - make
    - make dist
  artifacts:
    paths:
      - bridge-*.tar.gz
    expire_in: 1 week

# Building bridge for different systems with different version of slurm.
# Slurm versions must be named as they are in schedMD's download web site.
# DISTRIBUTION refers to a directory under `build` directory.
# The docker process of building must put the results of the build into
# a /dist directory that will be extracted.
build-parametric:
  variables:
    CI_CCC_NUM_CORES: "16"
  parallel:
    matrix:
      - DISTRIBUTION: [almalinux8, almalinux9]
        SLURM: [slurm-25.11.0, slurm-24.11.6, slurm-23.11.11, slurm-22.05.11]
  stage: build
  script:
    # we use a directory named against $DISTRIBUTION in which we have
    # our Dockerfile used to build bridge
    - cd build/$DISTRIBUTION
    # Getting slurm form the source
    - docker run --rm curlimages/curl -s https://download.schedmd.com/slurm/$SLURM.tar.bz2 >$SLURM.tar.bz2
    # Extracting slurm.spec from source to be used in the Dockerfiles
    - tar jOxvf $SLURM.tar.bz2 $SLURM/slurm.spec  > slurm.spec
    # Copying bridge source and bridge spec file built in build-dist job
    - cp ../../bridge-*.tar.gz .
    - cp ../../bridge.spec .
    # Creating the directory where we will put our builds results
    - mkdir $DISTRIBUTION-$SLURM
    # Building with a tag in order to be able to run it
    - docker build --tag $DISTRIBUTION-$SLURM .
    # Running the build to extract the /dist directory
    - docker run --rm $DISTRIBUTION-$SLURM tar -cC /dist . | tar -xC $DISTRIBUTION-$SLURM/
    # Moving it to get cleaner artifacts
    - mv $DISTRIBUTION-$SLURM/ ../../
  artifacts:
    name: $DISTRIBUTION-$SLURM
    paths:
      - $DISTRIBUTION-$SLURM/bridge-*.rpm
    expire_in: 1 week
  dependencies:
      - build-dist
