#!/bin/ksh
#*****************************************************************************\
#  scripts/common/bridge_toolbox - 
#******************************************************************************
#  Copyright  CEA/DAM/DIF (2012)
#
#  This file is part of Bridge, an abstraction layer to ease batch system and
#  resource manager usage in heterogeneous HPC environments.
#
#  Bridge is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Bridge is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Bridge.  If not, see <http://www.gnu.org/licenses/>
#*****************************************************************************/

#
#
#--------------------------------------------------------------------------------
# bridge_tmpfile : creer et affiche un nom de fichier temporaire unique 
# a partir de l'argument fournit
# usage : bridge_tmpfile <prefix>
# retour : nom du fichier temporaire
#--------------------------------------------------------------------------------
function bridge_tmpfile {
    typeset BRIDGE_OUTPUT
    typeset template=default
    if [ $# -ne 0 ]
	then
	template=$1
    fi
    BRIDGE_OUTPUT=$(mktemp ${template}_XXXXXX 2>&1)
    if [[ $? -ne 0 ]]
	then
	${ERROR} "Impossible de creer le fichier temporaire ${template}_XXXXXX : ${BRIDGE_OUTPUT:--}"
	return 1
    else
	echo ${BRIDGE_OUTPUT}
	return 0
    fi
}

###################################################################################################################
# bridge_get_memlimit : convertit en Mo le parametre d'entree et affiche la valeur obtenue
# usage : bridge_get_memlimit quantite
# retour : quantite en Mo
#------------------------------------------------------------------------------------------------------------------
function bridge_get_memlimit {
  integer VALUE
  integer MEM
  VALUE=`echo $1 | tr -d "[a-z][A-Z]"`
  UNITE=`echo $1 | tr -d "[0-9]"`
  case "$UNITE" in
    ko | Ko | kO | KO ) MEM=$VALUE/1024 ;;
    kw | Kw | kW | KW ) MEM=$VALUE*8/1024 ;;
    "" | mo | Mo | mO | MO | mb | Mb | MB | mB ) MEM=$VALUE ;;
    mw | Mw | mW | MW ) MEM=$VALUE*8 ;;
    go | Go | gO | GO ) MEM=$VALUE*1024 ;;
    gw | Gw | GW | Gw ) MEM=$VALUE*1024*8 ;;
    *) MEM=-1 ;;
  esac
  echo $MEM
}
