#!/bin/sh

export BRIDGE_MPRUN_JOBID=${RMS_RESOURCE}
export BRIDGE_MPRUN_STEPID=${RMS_JOBID}

export BRIDGE_MPRUN_NNODE=${RMS_NNODES}
export BRIDGE_MPRUN_NPROC=${RMS_NPROCS}
export BRIDGE_MPRUN_NCORE=${RMS_NCPUS}

export BRIDGE_MPRUN_QUEUE=${RMS_PARTITION}

export BRIDGE_MPRUN_NODEID=${RMS_NODEID}
export BRIDGE_MPRUN_PROCID=${RMS_LOCALID}
export BRIDGE_MPRUN_RANKID=${RMS_PROCID}

# not set in RMS
# values will be inherited from mprun command
#export BRIDGE_MPRUN_PROJECT=
