#!/bin/sh

export BRIDGE_MPRUN_REQID=${SLURM_JOB_ID}

export BRIDGE_MPRUN_NNODE=${SLURM_NNODES}
export BRIDGE_MPRUN_NPROC=${SLURM_NPROCS}
export BRIDGE_MPRUN_NCORE=${SLURM_CPUS_PER_TASK}

export BRIDGE_MPRUN_QUEUE=$(squeue -o %P -h -j ${SLURM_JOB_ID})
export BRIDGE_MPRUN_PROJECT=$(squeue -o %a -h -j ${SLURM_JOB_ID})

export BRIDGE_MPRUN_NODEID=${SLURM_NODEID}

export BRIDGE_MPRUN_PROCID=${SLURM_LOCALID}
if [[ -n ${OMPI_COMM_WORLD_LOCAL_RANK} ]]
then
    export BRIDGE_MPRUN_PROCID=${OMPI_COMM_WORLD_LOCAL_RANK}
fi

export BRIDGE_MPRUN_RANKID=${SLURM_PROCID}
if [[ -n ${OMPI_COMM_WORLD_RANK} ]]
then
    export BRIDGE_MPRUN_RANKID=${OMPI_COMM_WORLD_RANK}
fi
